[build]
  command = "hugo"
  publish = "public"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.72.0" # if older, use format: 0.53 (no trailing zero)

[context.deploy-preview.environment]
  HUGO_VERSION = "0.72.0"

[context.production.environment]
  HUGO_VERSION = "0.72.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"